# Generated by Django 3.2 on 2022-08-07 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('virtual_sessions', '0002_alter_comment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_number', models.CharField(editable=False, max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('donation_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('donater_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donater', to=settings.AUTH_USER_MODEL)),
                ('donation_recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient', to='virtual_sessions.session')),
            ],
        ),
    ]
