# Generated by Django 3.2 on 2022-08-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_amount',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
        ),
    ]
