# Generated by Django 3.2 on 2022-04-20 15:32

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PH', 'Physical'), ('ME', 'Mental'), ('NU', 'Nutritional')], max_length=50)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('summary', models.TextField(max_length=200)),
                ('details', models.TextField()),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('event_day', models.CharField(choices=[('SU', 'Sunday'), ('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday')], max_length=50)),
                ('event_time', models.TimeField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_sessions', to=settings.AUTH_USER_MODEL)),
                ('signed_up', models.ManyToManyField(blank=True, related_name='attending_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
