# Generated by Django 3.2 on 2022-06-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='number_of_sessions',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
